# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BarsApp' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BarsApp

  

  platform :ios, '9.0'
  target 'BarsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BarsApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BarsApp-tvOS

  target 'BarsApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
